// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HotfixMessage8.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace ET {

}

#endregion Designer generated code
